import java.util.Scanner;
public class randomnumberguesser {
 
public static void main(String[] args) {
  
	Scanner scan=new Scanner(System.in);
 
	int num, randNum = RNG.rand(); // Initialize randNum 
									// with a random number generated by the function.
	int lowGuess = 0, highGuess = 100; // Declare and initialize lowGuess and also highGuess variables. 
	boolean validate;
	char ch= 'y'; 
	System.out.println(" NUMBER GUESSER:"); // Print header.
	System.out.println("\n \n"); 
	RNG.resetCount(); // Reset count to 0.

	while(ch == 'y') 
	{
 
// Take user input.
		System.out.println("Guess a number between "+ lowGuess + " and "+ highGuess + " ..."); 
		num =scan.nextInt(); 
// Validate user input.
validate = RNG.inputValidation(num, lowGuess, highGuess);
if(validate == true) 
{
	if(num == randNum) // If the guess matches the random number.
	{ 
		System.out.println("You guessed correct!! ");
		lowGuess = 0; highGuess = 100; // Reset lowGuess and highGuess. 
		randNum = RNG.rand(); // Generate a new random number. 
		System.out.println("Want to guess again: (y/n)"); 
		ch =scan.next().charAt(0);
 
	}
	else   
	{
		// If the guess does not match with the random number then
		// change the values of highGuess and lowGuess according to the random number presented.
		if(randNum < num)
		{
		highGuess = randNum + 1;
		}
		else 
		{
			lowGuess = randNum - 1;
		} 
		System.out.println("Wrong guess." + "\nTry Again.");
 
	}
 
}
 
	// Enter the number that is not between lowGuess and highGuess.
	else
	{ 
	continue; 
	}
 
}
 
 
	// Before exiting the program.
	System.out.println("Total number of guesses made...  ");
	System.out.println("\n "+"Thank you for playing");
	System.out.println("\n "+
						"\n "+
						"\n  Programmer's name:Chimaobi Okoro  "); 

 
	}
 
}
